### ISSUE TITLE
Clarify masking

### ISSUE THREAD

**Issue by AlinderS** [Lund-Observatory-Teaching/lundpython#78]
I think the explanation of masking in lesson 2 can be improved. In both the presentation and the manual, masking is only shown in the example of acting on a subset of elements in an array (with the `*=` operator). This slightly obfuscates what the mask is and how it works, it could be clearer.
I suggest something like
```
mask = arr % 2
subset_arr = arr[mask]
```
which can be shortened to
`subset_arr = arr[arr % 2]`
To show the basics of masking, and we also retain the current example to show that functionality.

**Comment by eerovaher** [comment]
One of the Dynamical Astronomy notebooks already has an exercise that deals with this topic.
